In [ ]:
#Description: scrape top 10 cryptocurrencies by market cap

In [1]:
#Import the libraries
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
#Create empty lists to store the data
crypto_name_list=[]
crypto_market_cap_list=[]
crypto_price_list=[]
crypto_circulating_supply_list=[]
crypto_symbol_list=[]

In [3]:
#Create an empty dataframe to help organize the data
df = pd.DataFrame()

In [4]:
#Create a Function to scrape the data
# Example: https://coinmarketcap.com/historical/20220403/
def scrape(date='20220403/'):
  #Get the URL of the website that we want to scrape
  URL= 'https://coinmarketcap.com/historical/'+date
  #Make a request tothe website
  webpage = requests.get(URL)
  #Parse the text from the we bsite
  soup = BeautifulSoup(webpage.text, 'html.parser')
  

  #Get the table row element
  tr =soup.find_all('tr',attrs={'class':'cmc-table-row'})
  
  #Create a count variable for the number of crypto currencies that we want to scrape
  count = 0
  #Loop through every row to gather the data/information
  for row in tr:

    #if the count is reached then break out of the loop

    if count == 10:
      
      break;

    count=count+1 #Increment count by 1

    #Store the name of cryptocurrency into a variable
    #Find the td element (or column) to later get the crypto currency name
    name_column = row.find('td', attrs={'class':'cmc-table__cell cmc-table__cell--sticky cmc-table__cell--sortable cmc-table__cell--left cmc-table__cell--sort-by__name'})

    crypto_name = name_column.find('a',attrs={'class':'cmc-table__column-name--name cmc-link'}).text.strip()
    #Store the coin market cap of the crypto currency or coin into a varible
    crypto_market_cap =row.find('td',attrs={'class':'cmc-table__cell cmc-table__cell--sortable cmc-table__cell--right cmc-table__cell--sort-by__market-cap'}).text.strip()
    crypto_price=row.find('td',attrs={'class':'cmc-table__cell cmc-table__cell--sortable cmc-table__cell--right cmc-table__cell--sort-by__price'}).text.strip()
    #Find and store the crypto supply and symbol
    crypto_circulating_supply_and_symbol=row.find('td',attrs={'class':'cmc-table__cell cmc-table__cell--sortable cmc-table__cell--right cmc-table__cell--sort-by__circulating-supply'}).text.strip()
    #Split the Data
    crypto_circulating_supply = crypto_circulating_supply_and_symbol.split(' ')[0]
    crypto_symbol=crypto_circulating_supply_and_symbol.split(' ')[1]

    




    #APPEND THE DATA TO THE LISTS
    crypto_name_list.append(crypto_name)
    crypto_market_cap_list.append(crypto_market_cap)
    crypto_price_list.append(crypto_price)
    crypto_circulating_supply_list.append(crypto_circulating_supply)
    crypto_symbol_list.append(crypto_symbol)

In [5]:
#Run the scrape function
scrape(date='20220403/')

In [6]:
#Store the data into a dataframe to help organize the data

df['Name']=crypto_name_list
df['Market Cap']=crypto_market_cap_list
df['Price'] = crypto_price_list
df['Circulating Supply'] = crypto_circulating_supply_list
df['Symbol'] = crypto_symbol_list

#Show the data
df

        Name           Market Cap       Price Circulating Supply Symbol
0    Bitcoin  $882,703,992,270.52  $46,453.57         19,001,856    BTC
1   Ethereum  $423,557,081,705.00   $3,522.83        120,231,936    ETH
2     Tether   $82,324,402,977.49       $1.00     82,301,930,534   USDT
3        BNB   $74,360,146,489.04     $450.35        165,116,761    BNB
4   USD Coin   $51,633,984,578.70       $1.00     51,629,119,959   USDC
5     Solana   $44,563,278,264.23     $136.78        325,813,733    SOL
6        XRP   $40,575,582,678.21      $0.843     48,135,209,660    XRP
7    Cardano   $40,012,506,060.12       $1.19     33,739,028,516    ADA
8      Terra   $39,928,188,006.62     $113.07        353,128,511   LUNA
9  Avalanche   $26,224,674,828.73      $98.08        267,386,507   AVAX